config/routes.rb
Lit::Engine.routes.draw do


  if Lit.api_enabled
    namespace :api do
      namespace :v1 do
        get '/last_change' => 'localizations#last_change'
        resources :locales, :only=>[:index]
        resources :localization_keys, :only=>[:index]
        resources :localizations, :only=>[:index] do
          get 'last_change', :on=>:collection
        end
      end
    end
  end
  resources :locales, :only=>[:index, :destroy] do
    put :hide, :on=>:member
  end
  resources :localization_keys, :only=>[:index, :destroy] do
    member do
      get :star
    end
    collection do
      get :starred
    end
    resources :localizations, :only=>[:edit, :update] do
      member do
        get :previous_versions
      end
    end
  end
  resources :sources do
    member do
      get :synchronize
      put :touch
    end
    resources :incomming_localizations, :only=>[:index, :destroy] do
      member do
        get :accept
      end
      collection do
        get :accept_all
        post :reject_all
      end
    end
  end

  root :to=>"dashboard#index"
end

app/models/lit/incomming_localization.rb
module Lit
  class IncommingLocalization < ActiveRecord::Base
    serialize :translated_value

    ## ASSOCIATIONS
    belongs_to :locale
    belongs_to :localization_key
    belongs_to :localization
    belongs_to :source

    unless defined?(::ActionController::StrongParameters)
      attr_accessible
    end

    ## BEFORE & AFTER
    before_create :set_localization_id


    def get_value
      self.translated_value
    end

    def full_key
      [self.locale_str, self.localization_key_str].join('.')
    end

    def accept
      if self.localization.present?
        self.localization.translated_value = self.translated_value
        self.localization.save
      else
        unless self.locale.present?
          self.locale = Lit::Locale.new
          self.locale.locale = self.locale_str
          self.locale.save!
        end
        unless self.localization_key.present?
          self.localization_key = Lit::LocalizationKey.new
          self.localization_key.localization_key = self.localization_key_str
          self.localization_key.save!
        end
        unless self.localization.present?
          self.localization = Lit::Localization.new
          self.localization.locale = self.locale
          self.localization.localization_key = self.localization_key
          self.localization.default_value = self.translated_value
          self.localization.save!
        end
      end
      self.destroy
    end

    def is_duplicate?(val)
      set_localization_id unless localization.present?
      if localization
        translated_value = localization.read_attribute_before_type_cast('translated_value')
        if localization.is_changed? && !translated_value.nil?
          translated_value == val
        else
          localization.read_attribute_before_type_cast('default_value') == val
        end
      else
        false
      end
    end

    private
      def set_localization_id
        if self.locale.present? and self.localization_key.present?
          self.localization = self.localization_key.localizations.where(:locale_id=>self.locale_id).first
        end
      end
  end
end

app/models/lit/locale.rb
module Lit
  class Locale < ActiveRecord::Base

    ## SCOPES
    scope :ordered, proc{ order('locale ASC') }
    scope :visible, proc{ where(:is_hidden=>false) }

    ## ASSOCIATIONS
    has_many :localizations, :dependent=>:destroy

    ## VALIDATIONS
    validates :locale,
              :presence=>true,
              :uniqueness=>true

    unless defined?(::ActionController::StrongParameters)
      ## ACCESSIBLE
      attr_accessible :locale, :flag_image
    end

    def to_s
      self.locale
    end

    def get_translated_percentage
      total = self.get_all_localizations_count
      total > 0 ? (self.get_changed_localizations_count * 100 / total) : 0
    end

    def get_changed_localizations_count
      self.localizations.changed.count(:id)
    end

    def get_all_localizations_count
      self.localizations.count(:id)
    end
  end
end

app/models/lit/localization_version.rb
module Lit
  class LocalizationVersion < ActiveRecord::Base
    serialize :translated_value

    ## ASSOCIATIONS
    belongs_to :localization

    def to_s
      self.translated_value
    end
  end
end

app/controllers/lit/api/v1/base_controller.rb
module Lit
  module Api
    module V1
      class BaseController < ActionController::Base
        layout nil
        respond_to :json
        before_filter :authenticate_requests!


        private
          def authenticate_requests!
            authenticate_or_request_with_http_token do |token, options|
              Lit.api_key == token
            end
          end
      end
    end
  end
end

app/controllers/lit/api/v1/locales_controller.rb
require_dependency "lit/api/v1/base_controller"

module Lit
  module Api
    module V1
      class LocalesController < Api::V1::BaseController
        def index
          @locales = Locale.all
          render :json=>@locales.as_json(:root=>false, :only=>[:id, :locale])
        end
      end
    end
  end
end

app/controllers/lit/api/v1/localization_keys_controller.rb
require_dependency "lit/api/v1/base_controller"

module Lit
  class Api::V1::LocalizationKeysController < Api::V1::BaseController
    def index
      @localization_keys = LocalizationKey
      if params[:after].present?
        @localization_keys = @localization_keys.after(DateTime.parse(params[:after])).to_a
      else
        @localization_keys = @localization_keys.all
      end
      render :json=>@localization_keys.as_json(:root=>false, :only=>[:id, :localization_key])
    end
  end
end

app/controllers/lit/api/v1/localizations_controller.rb
module Lit
  class Api::V1::LocalizationsController < Api::V1::BaseController
    def index
      @localizations = Localization
      if params[:after].present?
        @localizations = @localizations.after(DateTime.parse(params[:after])).to_a
      else
        @localizations = @localizations.all
      end
      render :json=>@localizations.as_json(:root=>false, :only=>[:id, :localization_key_id, :locale_id], :methods=>[:value, :localization_key_str, :locale_str])
    end

    def last_change
      @localization = Localization.order('updated_at DESC').first
      render :json=>@localization.as_json(:root=>false, :only=>[], :methods=>[:last_change])
    end
  end
end

app/controllers/lit/application_controller.rb
module Lit
  class ApplicationController < ActionController::Base
    before_filter :authenticate
    before_filter :stop_hits_counter
    after_filter :restore_hits_counter

    private
      def authenticate
        if current_user && current_user.admin?
          return true
        else
          redirect_to "/", alert: "Brak uprawnien!"
        end
      end

      def stop_hits_counter
        Lit.init.cache.stop_hits_counter
      end

      def restore_hits_counter
        Lit.init.cache.restore_hits_counter
      end
  end
end

app/controllers/lit/dashboard_controller.rb
require_dependency "lit/application_controller"

module Lit
  class DashboardController < ::Lit::ApplicationController
    def index
      @locales = Lit::Locale.ordered.visible
    end
  end
end

app/controllers/lit/incomming_localizations_controller.rb
require_dependency "lit/application_controller"

module Lit
  class IncommingLocalizationsController < ApplicationController
    before_filter :find_source

    def index
      @incomming_localizations = @source.incomming_localizations.all
    end

    def accept
      @incomming_localization = @source.incomming_localizations.find(params[:id].to_i)
      @incomming_localization.accept
      Lit.init.cache.refresh_key @incomming_localization.full_key
      redirect_to :back
    end

    def accept_all
      @source.incomming_localizations.each do |li|
        li.accept
        Lit.init.cache.refresh_key li.full_key
      end
      redirect_to :back
    end

    def reject_all
      @source.incomming_localizations.destroy_all
      redirect_to :back
    end

    def destroy
      @incomming_localization = @source.incomming_localizations.find(params[:id].to_i)
      @incomming_localization.destroy
      redirect_to source_incomming_localizations_path(@source)
    end

    private
      def find_source
        @source = Source.find(params[:source_id].to_i)
      end
  end
end

app/controllers/lit/locales_controller.rb
require_dependency "lit/application_controller"

module Lit
  class LocalesController < ApplicationController
    def index
      @locales = Locale.ordered.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @locales }
      end
    end
    
    def hide
      @locale = Locale.find(params[:id])
      @locale.is_hidden = !@locale.is_hidden?
      @locale.save
      respond_to :js
    end
  
    def destroy
      @locale = Locale.find(params[:id])
      @locale.destroy
  
      respond_to do |format|
        format.html { redirect_to locales_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/lit/localization_keys_controller.rb
module Lit
  class LocalizationKeysController < ::Lit::ApplicationController
    before_filter :get_localization_scope, :except=>[:destroy]

    def index
      get_localization_keys
    end

    def starred
      @scope = @scope.where(:is_starred=>true)

      if @scope.respond_to?(:page)
        @scope = @scope.page(params[:page])
      end
      get_localization_keys
      render :action=>:index
    end

    def star
      @localization_key = LocalizationKey.find params[:id].to_i
      @localization_key.is_starred = ! @localization_key.is_starred?
      @localization_key.save
      respond_to :js
    end

    def destroy
      @localization_key = LocalizationKey.find params[:id].to_i
      @localization_key.destroy
      I18n.backend.available_locales.each do |l|
        Lit.init.cache.delete_key "#{l}.#{@localization_key.localization_key}"
      end
      respond_to :js
    end

    private
      def get_localization_scope
        @search_options = params.slice(*valid_keys)
        @search_options[:include_completed] = '1' if @search_options.empty?
        @scope = LocalizationKey.uniq.preload(:localizations => :locale).search(@search_options)
      end

      def get_localization_keys
        key_parts = @search_options[:key_prefix].to_s.split('.').length
        @prefixes = @scope.reorder(nil).uniq.pluck(:localization_key).map{|lk| lk.split('.').shift(key_parts+1).join('.') }.uniq.sort
        if @search_options[:key_prefix].present?
          parts = @search_options[:key_prefix].split('.')
          @parent_prefix = parts[0,parts.length-1].join('.')
        end

        if @scope.respond_to?(:page)
          @localization_keys = @scope.page(params[:page])
        else
          @localization_keys = @scope.all
        end
      end

      def valid_keys
        %w( key include_completed key_prefix order )
      end

      def grouped_localizations
        @_grouped_localizations ||= begin
          {}.tap do |hash|
            @localization_keys.each do |lk|
              hash[lk] = {}
              lk.localizations.each do |l|
                hash[lk][l.locale.locale.to_sym] = l
              end
            end
          end
        end
      end

      def localization_for(locale, localization_key)
        @_localization_for ||= {}
        key = [locale, localization_key]
        ret = @_localization_for[key]
        if ret == false
          nil
        elsif ret.nil?
          ret = grouped_localizations[localization_key][locale]
          unless ret
            Lit.init.cache.refresh_key("#{locale}.#{localization_key.localization_key}")
            ret = localization_key.localizations.where(:locale_id=>Lit.init.cache.find_locale(locale).id).first
          end
          @_localization_for[key] = ret ? ret : false
        else
          ret
        end

      end

      helper_method :localization_for

      def has_versions?(localization)
        @_versions ||= begin
          ids = grouped_localizations.values.map(&:values).flatten.map(&:id)
          Lit::Localization.where(:id => ids).joins(:versions).group("#{Lit::Localization.quoted_table_name}.id").count
        end
        @_versions[localization.id].to_i > 0
      end

      helper_method :has_versions?
  end
end

app/controllers/lit/localizations_controller.rb
module Lit
  class LocalizationsController < ::Lit::ApplicationController
    before_filter :find_localization_key
    before_filter :find_localization

    def edit
      @localization.translated_value = @localization.get_value
      respond_to :js
    end

    def update
      if @localization.update_attributes(clear_params)
        Lit.init.cache.update_cache @localization.full_key, @localization.get_value
      end
      @localization.reload
      respond_to :js
    end

    def previous_versions
      @versions = @localization.versions.order('created_at DESC')
      respond_to :js
    end

    private
      def find_localization_key
        @localization_key = Lit::LocalizationKey.find(params[:localization_key_id])
      end

      def find_localization
        @localization = @localization_key.localizations.find(params[:id])
      end

      def clear_params
        if defined?(::ActionController::StrongParameters)
          # allow translated_value to be an array
          if @localization.value.is_a?(Array)
            params.require(:localization).permit(:locale_id, :translated_value => [])
          else
            params.require(:localization).permit(:locale_id, :translated_value)
          end
        else
          params[:localization].is_a?(Hash) ? params[:localization].slice(:translated_value, :locale_id) : {}
        end
      end
  end
end

app/controllers/lit/sources_controller.rb
require_dependency "lit/application_controller"

module Lit
  class SourcesController < ApplicationController
    def index
      @sources = Source.all
    end

    def show
      @source = Source.find(params[:id])
    end

    def new
      @source = Source.new
    end

    def edit
      @source = Source.find(params[:id])
    end

    def synchronize
      @source = Source.find(params[:id])
      @source.synchronize
      redirect_to lit.source_incomming_localizations_path(@source)
    end

    def touch
      @source = Source.find(params[:id])
      @source.touch_last_updated_at!
      redirect_to request.env["HTTP_REFERER"].present? ? :back : @source
    end

    def create
      @source = Source.new(clear_params)
      if @source.save
        redirect_to @source, :notice => 'Source was successfully created.'
      else
        render :action => "new"
      end
    end

    def update
      @source = Source.find(params[:id])
      if @source.update_attributes(clear_params)
        redirect_to @source, :notice => 'Source was successfully updated.'
      else
        render :action => "edit"
      end
    end

    def destroy
      @source = Source.find(params[:id])
      @source.destroy
      redirect_to sources_url
    end

    private
      def clear_params
        if defined?(::ActionController::StrongParameters)
          params.require(:source).permit(:identifier, :url, :api_key)
        else
          params[:source]
        end
      end
  end
end

app/helpers/lit/application_helper.rb
module Lit
  module ApplicationHelper
    
  end
end

app/helpers/lit/dashboard_helper.rb
module Lit
  module DashboardHelper
  end
end

app/helpers/lit/localizations_helper.rb
module Lit
  module LocalizationsHelper
    def draw_icon(icon, opts={})
      raw("<i class=\"fa fa-#{icon} #{opts[:class]}\" title=\"#{opts[:title]}\" ></i>")
    end

    def ejs(val)
      escape_javascript val.to_s
    end

    def allow_wysiwyg_editor?(key)
      Lit.all_translations_are_html_safe || key.to_s =~ /(\b|_|\.)html$/
    end
  end
end

app/views/lit/localization_keys/_localization_row.html.erb
<% if localization.is_a?(Array) %>
  <ul>
    <% localization.each do |l| %>
      <li><%= l %></li>
    <% end %>
  </ul>
<% else %>
  <% if localization.nil? %>
    <em title="<%= t('.value_not_yet_translated', default: 'Value not yet translated') %>">null</em>
  <% else %>
    <%= localization %>
  <% end %>
<% end %>

app/views/lit/localization_keys/destroy.js.erb
$('tr.localization_key_row[data-id="<%= @localization_key.id %>"]').fadeOut();

app/views/lit/localization_keys/index.html.erb
<h3><%= t('.header', :default=>"Localization keys") %></h3>
<% available_locales = I18n.backend.available_locales %>

<table class="table">
  <%- @localization_keys.each do |lk| %>
    <tr class="localization_key_row" data-id="<%= lk.id %>">
      <td>
        <strong><%= lk.localization_key %></strong>
        <span class="badge"><%= Lit.init.cache.get_global_hits_counter(lk.localization_key) %></span>
        <div class="localization_keys_options">
          <%= link_to lit.star_localization_key_path(lk), :remote=>true, :class=>"star_icon" do %>
            <%= draw_icon lk.is_starred? ? 'star' : 'star-o' %>
          <% end %>
          <%= link_to lit.localization_key_path(lk), :method=>:delete, :data=>{:confirm=>t('lit.common.you_sure', :default=>"Are you sure?")}, :remote=>true do %>
            <%= draw_icon 'trash-o' %>
          <% end %>
        </div>
        <div class="detail_wrapper">
          <table class="table table-bordered table-striped">
            <%- available_locales.each do |locale| %>
              <%- localization = localization_for(locale, lk) %>
              <tr>
                <td class="localization_row" data-id="<%= localization.id%>" data-edit="<%= edit_localization_key_localization_path(lk, localization) %>" data-editing=0 data-content="">
                  <%= render :partial=>"localization_row", :locals=>{:localization=>Lit.init.cache["#{locale}.#{lk.localization_key}"]} %>
                </td>
                <td class="locale_row">
                  <%= image_tag("data:image/jpeg;base64, #{Base64.encode64(localization.locale.flag_image)}") rescue nil %>
                  <%= locale %>
                  <% if localization %>
                    <%= link_to lit.previous_versions_localization_key_localization_path(lk, localization), :class=>"show_prev_versions #{'hidden' unless has_versions?(localization)}", :remote=>true do %>
                      <%= draw_icon 'random', :title=>t('lit.common.previous_versions', :default=>"Previous versions") %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
              <tr class="hidden localization_versions_row" data-id="<%= localization.id %>">
                <td colspan="2" class="localization_versions"></td>
              </tr>
            <% end %>
          </table>
        </div>
      </td>
    </tr>
  <% end %>

</table>
<% if defined?(Kaminari)  %>
  <%= paginate @localization_keys, :theme=>"lit" %>
<% end %>
<% content_for(:sidebar) do %>
  <div class="well">
    <%= form_tag '', :class=>"form-search", :method=>:get do |f| %>
      <% if @search_options.has_key?(:key_prefix) %>
        <%= hidden_field_tag :key_prefix, @search_options[:key_prefix] %>
      <% end %>
      <div class="input-group">
        <%= text_field_tag :key, @search_options[:key], :class=>"form-control search-query" %>
        <div class="input-group-btn">
          <button type="submit" class="btn btn-default"><%= draw_icon 'search' %></button>
        </div>
      </div>
      <label class="checkbox">
        <%= check_box_tag :include_completed, '1', @search_options[:include_completed].to_i==1 %>
        <%= t('.is_completed', :default=>"Include completed") %>
      </label>
    <% end %>
    <ul class="nav nav-pills nav-stacked">
      <li class="<%= "active" if params[:action]=='index' %>">
        <%= link_to lit.localization_keys_path do -%>
          <%= draw_icon 'list' %>
          all
        <% end %>
      </li>
      <li class="<%= "active" if params[:action]=='starred' %>">
        <%= link_to lit.starred_localization_keys_path do -%>
          <%= draw_icon 'star' %>
          starred
        <% end %>
      </li>
      <li class="nav-header"><%= t(".order_by", :default => "Order by") %>:</li>
      <% Lit::LocalizationKey.order_options.each do |order| %>
        <li class="<%= "active" if order == @search_options[:order]  %>">
          <%= link_to url_for(@search_options.merge(:order => order)) do %>
            <%= t("lit.order_options.#{order.gsub(" ", "_")}", :default => order.humanize) %>
          <% end %>
        </li>
      <% end %>
      <li class="nav-header">Narrow with prefix</li>
      <% if @search_options[:key_prefix].present? %>
        <li>
          <%= link_to url_for(@search_options.merge(:key_prefix=>p)), :title=>(@parent_prefix.present? ? @parent_prefix : 'show all') do %>
            <%= draw_icon('chevron-left') %>
            <%= @parent_prefix.present? ? @parent_prefix.split('.').last : 'show all' %>
          <% end %>
        </li>
      <% end %>
      <% @prefixes.each do |p| %>
        <li class="key_prefix">
        <%= link_to url_for(@search_options.merge(:key_prefix=>p)) do %>
          <%= draw_icon('chevron-right') %>
          <%=  p.split('.').last %>
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/lit/localization_keys/star.js.erb
$('tr.localization_key_row[data-id="<%= @localization_key.id %>"] a.star_icon').html("<%= ejs(draw_icon(@localization_key.is_starred? ? 'star' : 'star-o')) %>");